### ISSUE TITLE
Breakage due to ASDF package changes

### ISSUE THREAD

**Issue by fare** [fukamachi/shelly#1]
Recent versions of ASDF do not export GETENV or any utilities anymore.
This breaks shelly.

The fix is to either
1- use ASDF-UTILS that exports all these utilities, or
2- use internal symbols like ASDF::GETENV if you really can't or won't depend on ASDF-UTILS.

Please test with a new ASDF (such as 2.25), without loading any system-provided ASDF via require.
My apologies for the breakage.

PS: You might be interested in my packages cl-launch, inferior-shell, lisp-invocation, xcvb-driver, command-line-arguments.

**Comment by fukamachi** [comment]
Thank you for letting me know that. I'll fix this in a few days.
