### ISSUE TITLE
Does not build - reference to QL:QUICKLOAD in source

### ISSUE THREAD

**Issue by quicklisp** [fukamachi/shelly#3]
QL functions are not available to use in libraries, so the QL:QUICKLOAD calls in versions.lisp signal an error.

http://report.quicklisp.org/shelly/2013-10-01/failtail.txt

I think if you want to use drakma, etc, they should be explicit dependencies of the project in the system definition.

**Comment by fukamachi** [comment]
Sorry and thank you for letting me know it.

> I think if you want to use drakma, etc, they should be explicit dependencies of the project in the system definition.

It is because Drakma, YASON and FLEXI-STREMES aren't always needed (See #2 for the details).

**Comment by snmsts** [comment]
I'm sorry Fukamachi-san I didn't notice.
